"""
Gestor de empaquetado de librerías para MiniML Engine.
Genera estructuras duales compatibles con PlatformIO (library.json)
y Arduino IDE (library.properties), resolviendo problemas de linkeo.
"""

import os
import zipfile
from datetime import datetime

class LibraryPackager:
    
    @staticmethod
    def create_arduino_zip(model_name, cpp_code, version="1.0.0", quantized=False, force=False, license_type="Apache-2.0"):
        """
        Crea ZIP estructurado para PlatformIO y Arduino.
        """
        safe_name = "".join(c for c in model_name if c.isalnum() or c == '_')
        lib_name = f"MiniML_{safe_name}"
        zip_filename = f"{lib_name}_v{version}.zip"
        
        export_path = os.path.join("exports", zip_filename)
        os.makedirs("exports", exist_ok=True)
        
        if os.path.exists(export_path) and not force:
            return {"success": False, "requires_confirm": True, "error": f"La librería '{zip_filename}' ya existe. ¿Deseas reemplazarla?"}

        desc_extra = " (INT8 Quantized)" if quantized else ""
        year = datetime.now().year

        try:
            with zipfile.ZipFile(export_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                
                # Código Fuente (Estructura Dual)
                # Guardamos en src/ para que ambos entornos lo detecten
                header_path = f"{lib_name}/src/{lib_name}.h"
                zipf.writestr(header_path, cpp_code)
                
                # Archivo .cpp auxiliar para evitar "Multiple Definitions" si se incluye en varios archivos
                cpp_stub = f"""#include "{lib_name}.h"\n// El motor MiniML opera de forma estática (Header-Only).\n"""
                zipf.writestr(f"{lib_name}/src/{lib_name}.cpp", cpp_stub)

                # Manifiesto para Arduino IDE
                props = (
                    f"name={lib_name}\n"
                    f"version={version}\n"
                    f"author=MiniML Engine Architect\n"
                    f"maintainer=MiniML Developer\n"
                    f"sentence=Edge AI Model{desc_extra} generated by MiniML Engine.\n"
                    f"paragraph=Optimized C++ inference engine for microcontrollers.\n"
                    f"category=Data Processing\n"
                    f"url=https://github.com/MiniML-Engine\n"
                    f"architectures=*\n"
                    f"depends=\n"
                )
                zipf.writestr(f"{lib_name}/library.properties", props)
                
                # Manifiesto para PlatformIO (library.json)
                pio_json = f"""{{
  "name": "{lib_name}",
  "version": "{version}",
  "description": "Edge AI Model{desc_extra} generated by MiniML Engine",
  "keywords": ["machine-learning", "tinyml", "ai", "miniml"],
  "repository": {{
    "type": "git",
    "url": "https://github.com/MiniML-Engine"
  }},
  "authors": [
    {{
      "name": "MiniML Engine Architect"
    }}
  ],
  "license": "{license_type}",
  "frameworks": ["arduino", "espidf", "mbed"],
  "platforms": ["atmelavr", "espressif32", "ststm32", "nordicnrf52"],
  "build": {{
    "flags": ["-O3"]
  }}
}}"""
                zipf.writestr(f"{lib_name}/library.json", pio_json)

                # Inyección de Licencia Open Source (Apache 2.0 por defecto)
                license_text = f"""Copyright {year} MiniML Engine Developer

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
                zipf.writestr(f"{lib_name}/LICENSE", license_text)

                # Ejemplo de Integración
                example = f"""/*
 * MiniML Engine - Inferencia Edge
 * Modelo: {safe_name}
 */
#include <Arduino.h>
#include "{lib_name}.h"

void setup() {{
    Serial.begin(115200);
    Serial.println("MiniML Model Initialized");
}}

void loop() {{
    // float input_data[] = {{ ... }};
    // float prediction = predict(input_data);
    delay(1000);
}}
"""
                zipf.writestr(f"{lib_name}/examples/BasicInference/BasicInference.ino", example)

            return {"success": True, "path": export_path}

        except Exception as e:
            return {"success": False, "error": str(e)}