"""
core/exporters/library_packer.py
--------------------------------
Gestor de empaquetado de librerías para EduBot Pro.
Convierte código fuente suelto en librerías .ZIP estándares
compatibles con el Gestor de Librerías de Arduino IDE.
"""

import os
import zipfile
from datetime import datetime

class LibraryPackager:
    
    @staticmethod
    def create_arduino_zip(model_name, cpp_code, version="1.0.0", quantized=False, force=False):
        """
        Crea ZIP Arduino. Si quantized=True, añade flag "Pro" en descripción.
        """
        safe_name = "".join(c for c in model_name if c.isalnum() or c == '_')
        lib_name = f"MiniML_{safe_name}"
        zip_filename = f"{lib_name}_v{version}.zip"
        export_path = os.path.join("exports", zip_filename)
        os.makedirs("exports", exist_ok=True)
        if os.path.exists(export_path) and not force:
            return {"success": False, "requires_confirm": True, "error": f"La librería '{zip_filename}' ya existe. ¿Deseas reemplazarla?"}

        desc_extra = " (INT8 Quantized)" if quantized else ""

        try:
            with zipfile.ZipFile(export_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                zipf.writestr(f"{lib_name}/src/{lib_name}.h", cpp_code)
                
                props = (
                    f"name={lib_name}\n"
                    f"version={version}\n"
                    f"author=MiniML Engine\n"
                    f"maintainer=User\n"
                    f"sentence=TinyML Model{desc_extra} generated by MiniML Engine.\n"
                    f"paragraph=Optimized inference engine for Arduino.\n"
                    f"category=Data Processing\n"
                    f"url=https://github.com/Shuuida/MiniML-Engine\n"
                    f"architectures=*\n"
                )
                zipf.writestr(f"{lib_name}/library.properties", props)
                
                # Ejemplo .ino simple
                example = f"""#include "{lib_name}.h"\n{safe_name} model;\nvoid setup() {{ Serial.begin(9600); }}\nvoid loop() {{}}"""
                zipf.writestr(f"{lib_name}/examples/Inference/Inference.ino", example)

            return {"success": True, "path": export_path}

        except Exception as e:
            return {"success": False, "error": str(e)}