"""
Generador de código Rust optimizado para MiniTensor
Soporta inferencia híbrida:
- Float32 (Legacy)
- INT8 Quantized (Industrial - MiniTensor)

Incluye soporte para:
- Linear, Conv2d (Per-Channel/Per-Tensor)
- MaxPool2d, Flatten, ReLU
- FakeQuant (QAT)
"""

import math

def _flatten(data_list):
    """Auxiliar para aplanar lista de listas recursivamente."""
    if isinstance(data_list, (list, tuple)):
        if len(data_list) == 0:
            return []
        if not isinstance(data_list[0], (list, tuple)):
            return data_list
        return [item for sublist in data_list for item in _flatten(sublist)]
    return [data_list]

def _get_val(param):
    """Extrae valor entero de int o list/tuple."""
    if isinstance(param, (list, tuple)): return int(param[0])
    return int(param)

def _get_kernel_dims(kernel_size):
    if isinstance(kernel_size, (list, tuple)): return kernel_size[0], kernel_size[1]
    k = int(kernel_size)
    return k, k

def generate_rust_code(model, input_shape, model_name="MiniModel"):
    """
    Genera código Rust (no_std) compatible con Arduino/Embedded.
    Detecta automáticamente si el modelo es un diccionario cuantizado (INT8)
    o un objeto MiniTensor (Float32).
    """
    
    # DETECCIÓN DE MODO
    is_quantized = isinstance(model, dict)
    
    code = []
    
    code.append("#![no_std]")
    code.append("// Auto-generated by MiniML Engine Rust Exporter")
    code.append(f"// Mode: {'QUANTIZED (INT8)' if is_quantized else 'FLOAT32'}")
    code.append("")
    
    code.append(f"pub struct {model_name};")
    code.append(f"impl {model_name} {{")

    inference_body = []
    
    # SETUP DE ENTRADA
    # Calcular tamaño plano
    input_flat_size = 1
    for dim in input_shape: input_flat_size *= dim
    
    inference_body.append(f"        let x0 = input;") 
    current_var = "x0"
    current_shape = list(input_shape)
    current_flat_size = input_flat_size

    # PREPARAR ITERADOR DE CAPAS
    if is_quantized:
        # Extraer capas del diccionario ordenadas por índice
        layers_data = []
        for k, v in model.items():
            if k == "__metadata__": continue
            try:
                idx = int(k.split('_')[1])
                layers_data.append((idx, k, v))
            except: continue
        layers_data.sort(key=lambda x: x[0])
        iterator = [(item[0], item[2]) for item in layers_data] # (idx, data_dict)
    else:
        # Modo Objeto
        iterator = enumerate(model.layers)

    # BUCLE DE GENERACIÓN DE CAPAS
    for i, layer_obj in iterator:
        
        # Normalizar acceso a datos
        if is_quantized:
            layer_type = layer_obj['type']
            data_src = layer_obj
            layer_quantized = layer_obj.get('quantized', False)
        else:
            layer_type = layer_obj.__class__.__name__
            layer_quantized = False
        
        # CAPA: LINEAR (Dense)
        if 'Linear' in layer_type:
            # Flatten Implícito si venimos de Conv
            if len(current_shape) > 1:
                current_shape = [current_flat_size]
                # No generamos código extra, Rust maneja memoria plana

            if is_quantized:
                # Recuperar datos del dict asumiendo forma (In, Out)
                w_list = data_src['weights']
                w_in = len(w_list)      
                w_out = len(w_list[0])   
                w_flat = _flatten(w_list)
                b_flat = _flatten(data_src['bias']) if data_src['bias'] else [0.0] * w_out
                
                # Escribir Constantes
                w_str = ", ".join(str(int(x)) for x in w_flat)
                code.append(f"    const W{i}: [i8; {len(w_flat)}] = [{w_str}];")
                
                if layer_quantized:
                    scales = _flatten(data_src['scale'])
                    zps = _flatten(data_src['zero_point'])
                    s_str = ", ".join(f"{x:.8f}" for x in scales)
                    z_str = ", ".join(str(int(x)) for x in zps)
                    
                    code.append(f"    const S{i}: [f32; {len(scales)}] = [{s_str}];")
                    code.append(f"    const Z{i}: [i8; {len(zps)}] = [{z_str}];")
            else:
                w_in, w_out = layer_obj.weights.shape
                w_flat = _flatten(layer_obj.weights.data)
                b_flat = _flatten(layer_obj.bias.data) if layer_obj.bias else [0.0] * w_out
                
                w_str = ", ".join(f"{x:.6f}" for x in w_flat)
                code.append(f"    const W{i}: [f32; {len(w_flat)}] = [{w_str}];")
            
            # Bias (siempre f32)
            b_str = ", ".join(f"{x:.6f}" for x in b_flat)
            code.append(f"    const B{i}: [f32; {len(b_flat)}] = [{b_str}];")

            next_var = f"x{i+1}"
            inference_body.append(f"")
            inference_body.append(f"        // --- Linear ({w_in} -> {w_out}) ---")
            inference_body.append(f"        let mut {next_var} = Self::B{i};") # Init con Bias

            # Bucle de Inferencia Corregido
            inference_body.append(f"        for out_c in 0..{w_out} {{")
            
            if layer_quantized:
                if data_src['scheme'] == 'per_channel':
                    inference_body.append(f"            let s = Self::S{i}[out_c];")
                    inference_body.append(f"            let z = Self::Z{i}[out_c] as f32;")
                else:
                    inference_body.append(f"            let s = Self::S{i}[0];")
                    inference_body.append(f"            let z = Self::Z{i}[0] as f32;")
                
                inference_body.append(f"            for in_c in 0..{w_in} {{")
                inference_body.append(f"                let w_raw = Self::W{i}[in_c * {w_out} + out_c] as f32;")
                inference_body.append(f"                let w_val = (w_raw - z) * s;")
                inference_body.append(f"                {next_var}[out_c] += {current_var}[in_c] * w_val;")
                inference_body.append(f"            }}")
            else:
                # Loop Float Standard
                inference_body.append(f"            for in_c in 0..{w_in} {{")
                inference_body.append(f"                {next_var}[out_c] += {current_var}[in_c] * Self::W{i}[in_c * {w_out} + out_c];")
                inference_body.append(f"            }}")
                
            inference_body.append(f"        }}")
            
            current_var = next_var
            current_shape = [w_out]
            current_flat_size = w_out

        # CAPA: CONV2D
        elif 'Conv2d' in layer_type:
            if is_quantized:
                w_list = data_src['weights']
                out_ch = len(w_list)
                in_ch = len(w_list[0])
                
                # Fix: Usar metadatos seguros del Quantizer
                if 'kernel_size' in data_src:
                    ks = data_src['kernel_size']
                    kh, kw = _get_kernel_dims(ks)
                else:
                    # Fallback (solo si la estructura es antigua)
                    kh = len(w_list[0][0])
                    kw = len(w_list[0][0][0])

                w_flat = _flatten(w_list)
                b_flat = _flatten(data_src['bias']) if data_src['bias'] else [0.0]*out_ch
                
                w_str = ", ".join(str(int(x)) for x in w_flat)
                code.append(f"    const W{i}: [i8; {len(w_flat)}] = [{w_str}];")
                if layer_quantized:
                    scales = _flatten(data_src['scale'])
                    zps = _flatten(data_src['zero_point'])
                    s_str = ", ".join(f"{x:.8f}" for x in scales)
                    z_str = ", ".join(str(int(x)) for x in zps)
                    code.append(f"    const S{i}: [f32; {len(scales)}] = [{s_str}];")
                    code.append(f"    const Z{i}: [i8; {len(zps)}] = [{z_str}];")
                
                stride = _get_val(data_src.get('stride', 1))
                padding = _get_val(data_src.get('padding', 1))
            else:
                out_ch = layer_obj.out_channels
                in_ch = layer_obj.in_channels
                kh, kw = _get_kernel_dims(layer_obj.kernel_size)
                stride = _get_val(layer_obj.stride)
                padding = _get_val(layer_obj.padding)
                w_flat = _flatten(layer_obj.weights.data)
                b_flat = _flatten(layer_obj.bias.data) if layer_obj.bias else [0.0]*out_ch
                w_str = ", ".join(f"{x:.6f}" for x in w_flat)
                code.append(f"    const W{i}: [f32; {len(w_flat)}] = [{w_str}];")
            
            b_str = ", ".join(f"{x:.6f}" for x in b_flat)
            code.append(f"    const B{i}: [f32; {len(b_flat)}] = [{b_str}];")

            if len(current_shape) == 3: 
                in_c, in_h, in_w = current_shape
            else:
                # Fallback para entrada plana
                in_c = in_ch # Usamos el canal extraído de los pesos
                side = int(math.sqrt(current_flat_size / in_c))
                in_h, in_w = side, side

            out_h = int((in_h + 2 * padding - kh) / stride + 1)
            out_w = int((in_w + 2 * padding - kw) / stride + 1)
            output_vol = out_ch * out_h * out_w

            next_var = f"x{i+1}"
            inference_body.append(f"        let mut {next_var} = [0.0; {output_vol}];")

            loop_code = f"""        for och in 0..{out_ch} {{
            let bias = Self::B{i}[och];
            """
            if layer_quantized:
                idx = "och" if data_src['scheme'] == 'per_channel' else "0"
                loop_code += f"            let s = Self::S{i}[{idx}];\\n"
                loop_code += f"            let z = Self::Z{i}[{idx}] as f32;\\n"
            
            loop_code += f"""            for oy in 0..{out_h} {{
                for ox in 0..{out_w} {{
                    let mut sum = bias;
                    let in_start_y = (oy * {stride}) as isize - {padding};
                    let in_start_x = (ox * {stride}) as isize - {padding};
                    for ich in 0..{in_c} {{
                        for ky in 0..{kh} {{
                            for kx in 0..{kw} {{
                                let iy = in_start_y + ky as isize;
                                let ix = in_start_x + kx as isize;
                                if iy >= 0 && iy < {in_h} && ix >= 0 && ix < {in_w} {{
                                    let input_idx = (ich * {in_h} * {in_w}) + (iy as usize * {in_w}) + ix as usize;
                                    let weight_idx = (och * {in_c} * {kh} * {kw}) + (ich * {kh} * {kw}) + (ky * {kw}) + kx;
                                    """
            if layer_quantized:
                loop_code += f"""let w_raw = Self::W{i}[weight_idx] as f32;
                                    let w_val = (w_raw - z) * s;
                                    sum += {current_var}[input_idx] * w_val;"""
            else:
                loop_code += f"""sum += {current_var}[input_idx] * Self::W{i}[weight_idx];"""
            loop_code += f"""
                                }}
                            }}
                        }}
                    }}
                    {next_var}[(och * {out_h} * {out_w}) + (oy * {out_w}) + ox] = sum;
                }}
            }}
        }}"""
            inference_body.append(loop_code)
            current_var = next_var
            current_shape = [out_ch, out_h, out_w]
            current_flat_size = output_vol

        # CAPA: MAXPOOL2D
        elif 'MaxPool' in layer_type:
            # Recuperar hiperparámetros
            if is_quantized:
                k_val = data_src.get('kernel_size', 2)
                kh, kw = (k_val, k_val) if isinstance(k_val, int) else (k_val[0], k_val[1])
                stride = data_src.get('stride', 2)
            else:
                kh, kw = (layer_obj.kernel_size, layer_obj.kernel_size) if isinstance(layer_obj.kernel_size, int) else layer_obj.kernel_size
                stride = layer_obj.stride if layer_obj.stride else kh

            # Geometría
            if len(current_shape) == 3:
                in_c, in_h, in_w = current_shape
            else:
                # Fallback seguro
                side = int(math.sqrt(current_flat_size)) 
                # Asumimos canales = 1 si se perdió la forma, o intentamos inferir
                # Para robustez v3.0, usamos la shape rastreada
                in_c, in_h, in_w = current_shape if len(current_shape)==3 else (1, side, side)

            out_h = int((in_h - kh) / stride + 1)
            out_w = int((in_w - kw) / stride + 1)
            output_vol = in_c * out_h * out_w

            next_var = f"x{i+1}"
            inference_body.append(f"")
            inference_body.append(f"        // --- MaxPool ({kh}x{kw}) ---")
            inference_body.append(f"        let mut {next_var} = [0.0; {output_vol}];")
            
            # Bucle MaxPool Rust
            loop_code = f"""        for ch in 0..{in_c} {{
            for oy in 0..{out_h} {{
                for ox in 0..{out_w} {{
                    let mut max_val = -3.40282347e+38; // f32::MIN approx
                    
                    let start_y = oy * {stride};
                    let start_x = ox * {stride};
                    
                    for ky in 0..{kh} {{
                        for kx in 0..{kw} {{
                            let iy = start_y + ky;
                            let ix = start_x + kx;
                            
                            if iy < {in_h} && ix < {in_w} {{
                                let idx = (ch * {in_h} * {in_w}) + (iy * {in_w}) + ix;
                                let val = {current_var}[idx];
                                if val > max_val {{ max_val = val; }}
                            }}
                        }}
                    }}
                    
                    let out_idx = (ch * {out_h} * {out_w}) + (oy * {out_w}) + ox;
                    {next_var}[out_idx] = max_val;
                }}
            }}
        }}"""
            inference_body.append(loop_code)
            
            current_var = next_var
            current_shape = [in_c, out_h, out_w]
            current_flat_size = output_vol

        # CAPA: FLATTEN
        elif 'Flatten' in layer_type:
            inference_body.append(f"        // --- Flatten Layer (Logical Only) ---")
            current_shape = [current_flat_size]

        # ACTIVACIÓN: RELU
        elif 'ReLU' in layer_type:
            inference_body.append(f"        // --- ReLU Activation (in-place) ---")
            inference_body.append(f"        for val in {current_var}.iter_mut() {{ if *val < 0.0 {{ *val = 0.0; }} }}")

        # ACTIVACIÓN: SIGMOID
        elif 'Sigmoid' in layer_type:
            inference_body.append(f"        // --- Sigmoid Activation (in-place) ---")
            inference_body.append(f"        for val in {current_var}.iter_mut() {{")
            inference_body.append(f"            if *val > 100.0 {{ *val = 100.0; }}")
            inference_body.append(f"            if *val < -100.0 {{ *val = -100.0; }}")
            # Nota: En entornos bare-metal no_std, .exp() requiere el crate 'micromath'
            inference_body.append(f"            *val = 1.0 / (1.0 + (-*val).exp());")
            inference_body.append(f"        }}")

        # > CAPA MAXPOOL 1D
        elif 'MaxPool1d' in layer_type:
            channels = current_shape[0] if len(current_shape) > 1 else 1
            in_len = current_shape[1] if len(current_shape) > 1 else current_shape[0]
            k_size = data_src.get('kernel_size', 2)
            stride = data_src.get('stride', k_size)
            
            out_len = (in_len - k_size) // stride + 1
            
            next_var = f"x{i+1}"
            inference_body.append(f"        // --- MaxPool1D (K:{k_size}, S:{stride}) ---")
            inference_body.append(f"        let mut {next_var} = [0.0f32; {channels * out_len}];")
            
            loop = f"""        for c in 0..{channels} {{
            for l in 0..{out_len} {{
                let mut max_val = -f32::INFINITY;
                for k in 0..{k_size} {{
                    let in_idx = l * {stride} + k;
                    if in_idx < {in_len} {{
                        let val = {current_var}[c * {in_len} + in_idx];
                        if val > max_val {{ max_val = val; }}
                    }}
                }}
                {next_var}[c * {out_len} + l] = max_val;
            }}
        }}"""
            inference_body.append(loop)
            
            current_var = next_var
            current_shape = [channels, out_len]
            current_flat_size = channels * out_len

        # > CAPA CONV1D
        elif 'Conv1d' in layer_type:
            in_channels = current_shape[0] if len(current_shape) > 1 else 1
            in_len = current_shape[1] if len(current_shape) > 1 else current_shape[0]
            
            out_channels = data_src.get('out_channels', layer_obj.weights.shape[0] if hasattr(layer_obj, 'weights') else 1)
            k_size = data_src.get('kernel_size', layer_obj.weights.shape[2] if hasattr(layer_obj, 'weights') else 1)
            stride = data_src.get('stride', 1)
            
            out_len = (in_len - k_size) // stride + 1
            
            w_flat = _flatten(data_src['weights']) if 'weights' in data_src else _flatten(layer_obj.weights.data)
            b_flat = _flatten(data_src['bias']) if data_src.get('bias') else [0.0] * out_channels
            
            w_str = ", ".join(f"{x:.6f}" for x in w_flat)
            b_str = ", ".join(f"{x:.6f}" for x in b_flat)
            
            code.append(f"    const W{i}: [f32; {len(w_flat)}] = [{w_str}];")
            code.append(f"    const B{i}: [f32; {len(b_flat)}] = [{b_str}];")
            
            next_var = f"x{i+1}"
            inference_body.append(f"        // --- Conv1D ({in_channels} -> {out_channels}, K:{k_size}, S:{stride}) ---")
            inference_body.append(f"        let mut {next_var} = [0.0f32; {out_channels * out_len}];")
            
            loop = f"""        for out_c in 0..{out_channels} {{
            for l in 0..{out_len} {{
                let mut sum = Self::B{i}[out_c];
                
                for in_c in 0..{in_channels} {{
                    for k in 0..{k_size} {{
                        let in_idx = l * {stride} + k;
                        let w_idx = out_c * ({in_channels} * {k_size}) + in_c * {k_size} + k;
                        sum += {current_var}[in_c * {in_len} + in_idx] * Self::W{i}[w_idx];
                    }}
                }}
                {next_var}[out_c * {out_len} + l] = sum;
            }}
        }}"""
            inference_body.append(loop)
            
            current_var = next_var
            current_shape = [out_channels, out_len]
            current_flat_size = out_channels * out_len

        # > BLOQUE RESIDUAL 1D
        elif 'ResidualBlock1D' in layer_type:
            channels = current_shape[0] if len(current_shape) > 1 else 1
            in_len = current_shape[1] if len(current_shape) > 1 else current_shape[0]
            
            # Accedemos a los pesos desde layer_obj al ser una clase no estándar
            w_flat = _flatten(layer_obj.conv.weights.data)
            b_flat = _flatten(layer_obj.conv.bias.data) if layer_obj.conv.bias else [0.0] * channels
            
            w_str = ", ".join(f"{x:.6f}" for x in w_flat)
            b_str = ", ".join(f"{x:.6f}" for x in b_flat)
            
            # Constantes en Flash
            code.append(f"    const W_RES_{i}: [f32; {len(w_flat)}] = [{w_str}];")
            code.append(f"    const B_RES_{i}: [f32; {len(b_flat)}] = [{b_str}];")
            
            next_var = f"x{i+1}"
            inference_body.append(f"        // --- ResidualBlock1D (Channels: {channels}) ---")
            inference_body.append(f"        let mut {next_var} = [0.0f32; {channels * in_len}];")
            
            # Bucle fusionado (Conv1x1 -> ReLU -> Skip Connection)
            loop = f"""        for out_c in 0..{channels} {{
            for l in 0..{in_len} {{
                let mut sum = Self::B_RES_{i}[out_c];
                
                for in_c in 0..{channels} {{
                    let w_val = Self::W_RES_{i}[out_c * {channels} + in_c];
                    sum += {current_var}[in_c * {in_len} + l] * w_val;
                }}
                
                if sum < 0.0 {{ sum = 0.0; }} // ReLU
                
                // Skip Connection: Sumamos entrada original
                {next_var}[out_c * {in_len} + l] = sum + {current_var}[out_c * {in_len} + l];
            }}
        }}"""
            inference_body.append(loop)
            
            current_var = next_var
            current_shape = [channels, in_len]
            current_flat_size = channels * in_len

        # FAKE QUANT (QAT)
        elif 'FakeQuant' in layer_type:
            # Si estamos en modo quantized, esto es redundante, pero soportamos QAT explícito
            if not is_quantized: # Solo para legacy object mode con QAT
                if layer_obj.scale is not None:
                    scale_data = layer_obj.scale.data
                    is_per_channel = len(scale_data) > 1 and len(scale_data[0]) > 1 # Simple check
                    
                    scales_flat = _flatten(scale_data)
                    s_str = ", ".join(f"{x:.6f}" for x in scales_flat)
                    code.append(f"    const S{i}: [f32; {len(scales_flat)}] = [{s_str}];")
                    
                    inference_body.append(f"        // --- FakeQuant (QAT Simulation) ---")
                    
                    if is_per_channel:
                         # Asumimos channel dim es 0 del current tensor
                         dim_0 = current_shape[0]
                         stride_size = int(current_flat_size / dim_0)
                         inference_body.append(f"        for ch in 0..{dim_0} {{")
                         inference_body.append(f"            let s = Self::S{i}[ch];")
                         inference_body.append(f"            for k in 0..{stride_size} {{")
                         inference_body.append(f"                let idx = ch * {stride_size} + k;")
                         inference_body.append(f"                {current_var}[idx] = ({current_var}[idx] / s).round() * s;")
                         inference_body.append(f"            }}")
                         inference_body.append(f"        }}")
                    else:
                        inference_body.append(f"        let s = Self::S{i}[0];")
                        inference_body.append(f"        for val in {current_var}.iter_mut() {{")
                        inference_body.append(f"            *val = (*val / s).round() * s;")
                        inference_body.append(f"        }}")

    code.append("")
    code.append(f"    pub fn predict(input: &[f32; {input_flat_size}]) -> [f32; {current_flat_size}] {{")
    code.extend(inference_body)
    code.append(f"        {current_var}")
    code.append("    }")
    code.append("}")
    
    return "\n".join(code)